export type Id = string;

export enum LINE_VALUE {
  "NORMAL" = "NORMAL",
  "HIGH_VALUE" = "HIGH_VALUE",
  "HIGHEST_VALUE" = "HIGHEST_VALUE",
}

export enum EVENT_TYPE {
  "APPOINTMENT" = "APPOINTMENT",
  "OCCURRENCE" = "OCCURRENCE",
  "SURGERY" = "SURGERY",
  "TEST" = "TEST",
}

export enum ECheckTokenMessage {
  "TOKEN_VALID" = "TOKEN_VALID",
  "TOKEN_INVALID" = "TOKEN_INVALID",
  "TOKEN_EXPIRED" = "TOKEN_EXPIRED",
}

export enum EResetPasswordMessage {
  "EMAIL_IS_REQUIRED" = "EMAIL_IS_REQUIRED",
  "EMAIL_SENT" = "EMAIL_SENT",
  "EMAIL_SENT_ERROR" = "EMAIL_SENT_ERROR",
  "INTERNAL_ERROR" = "INTERNAL_ERROR",
}

export enum ESetNewPasswordMessage {
  "TOKEN_IS_REQUIRED" = "TOKEN_IS_REQUIRED",
  "PASSWORD_IS_REQUIRED" = "PASSWORD_IS_REQUIRED",
  "TOKEN_INVALID" = "TOKEN_INVALID",
  "TOKEN_EXPIRED" = "TOKEN_EXPIRED",
  "USER_DOES_NOT_EXISTS" = "USER_DOES_NOT_EXISTS",
  "NEW_PASSWORD_SET" = "NEW_PASSWORD_SET",
}
